# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d68aabe6824d21881759ddc7815d0c2f"
application_url = "https://hair-sells-rare-trips.trycloudflare.com"
embedded = true
name = "ex-delievry"
handle = "ex-delievry"

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_assigned_fulfillment_orders,read_content,read_customers,read_delivery_customizations,read_merchant_managed_fulfillment_orders,read_orders,read_products,read_script_tags,read_shipping,read_themes,read_third_party_fulfillment_orders,write_assigned_fulfillment_orders,write_content,write_customers,write_delivery_customizations,write_merchant_managed_fulfillment_orders,write_orders,write_products,write_script_tags,write_shipping,write_themes,write_third_party_fulfillment_orders"

[auth]
redirect_urls = [
  "https://hair-sells-rare-trips.trycloudflare.com/auth/callback",
  "https://hair-sells-rare-trips.trycloudflare.com/auth/shopify/callback",
  "https://hair-sells-rare-trips.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://hair-sells-rare-trips.trycloudflare.com/customapi"
subpath = "proxy-8"
prefix = "apps"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
