# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "114ba644127ad3f4278c8e384c114827"
application_url = "https://sufficient-greatly-racial-evaluation.trycloudflare.com"
embedded = true
name = "ez-delievry"
handle = "ez-delievry"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "paymenttest-store.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_assigned_fulfillment_orders,read_content,read_customers,read_delivery_customizations,read_merchant_managed_fulfillment_orders,read_orders,read_products,read_script_tags,read_shipping,read_themes,read_third_party_fulfillment_orders,write_assigned_fulfillment_orders,write_content,write_customers,write_delivery_customizations,write_merchant_managed_fulfillment_orders,write_orders,write_products,write_script_tags,write_shipping,write_themes,write_third_party_fulfillment_orders"

[auth]
redirect_urls = [
  "https://sufficient-greatly-racial-evaluation.trycloudflare.com/auth/callback",
  "https://sufficient-greatly-racial-evaluation.trycloudflare.com/auth/shopify/callback",
  "https://sufficient-greatly-racial-evaluation.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
