# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d68aabe6824d21881759ddc7815d0c2f"
application_url = "https://relaxation-survive-campaigns-description.trycloudflare.com"
embedded = true
name = "ex-delievry"
handle = "ex-delievry"

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_locales,read_products,read_script_tags,read_themes,write_content,write_locales,write_products,write_script_tags,write_themes"

[auth]
redirect_urls = [
  "https://relaxation-survive-campaigns-description.trycloudflare.com/auth/callback",
  "https://relaxation-survive-campaigns-description.trycloudflare.com/auth/shopify/callback",
  "https://relaxation-survive-campaigns-description.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "methodui.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
